### PR TITLE
Laravel 5.7 upgrade

### PR DESCRIPTION
**Pull request by evocate**

### CODE REVIEW

**Comment by billythekid** [comment]
should have made these 5 separate PRs for Hacktoberfest https://hacktoberfest.digitalocean.com/stats/evocate

**Comment by sunscreem** [comment]
Ooo - look at that. I mean - the stats are rubbish but the page looks cool!

**Comment by sunscreem** [comment]
I'll check this and merge tomorrow. Might even set up a test or 3 if I can be hooped.

**Review by sunscreem — APPROVED** [review]

**Comment by sunscreem** [comment]
@evocate FYI - https://github.com/laravel/framework/issues/20617#issuecomment-421771983

Missed a couple of changing `or` to `??` 

https://github.com/AberdeenPHP/AberdeenPHP-Website/commit/72896f9019f5d2131b7214a8c42d45c58a5782e2

**Pull request merged**
