### PR TITLE
Fix for a fix, community page, re #52 and #46

### PR DESCRIPTION
**Pull request by AndyGaskell**
Fix to layout of https://aberdeenphp.co.uk/community

Makes layout better, as per #46 
Fixes the images stepping glitch, spotted in #52

### CODE REVIEW

**Comment by AndyGaskell** [comment]
Hey @sunscreem, here's that fix :)

**Review by sunscreem — APPROVED** [review]

**Comment by sunscreem** [comment]
Hmm - I've just put that live and I'm still getting the stepping images problem?
(I'll leave it live for now so you can spot it?)

**Comment by AndyGaskell** [comment]
Ah, looks ok in Firefox, seems like it needs a few more pixels in Chrome though.  I'll do another PR just now to fix the fix

**Comment by AndyGaskell** [comment]
Couple of new PRs for this #54 and #55, not sure why that came as two separate PRs, just me making a git of it

**Pull request merged**
