### PR TITLE
updating svg and sizing

### PR DESCRIPTION
**Pull request by dannyockilson**
Are there any other places the logo is used? Could only find it used in the header... I've switched it out for the svg and bumped the size up a little.

RE: https://github.com/AberdeenPHP/AberdeenPHP-Website/issues/19#issuecomment-286899709

### CODE REVIEW

**Comment by sunscreem** [comment]
Look at that - Andy's like FUCK IT - MERGE NOW.

I've nae even tested in yet lol

**Comment by AndyGaskell** [comment]
It worked for me :)

**Comment by AndyGaskell** [comment]
Let me know if you want to test each merge yourself.  I tested this, so it seemed ok to merge.

**Comment by sunscreem** [comment]
Its cool.. Danny could have just committed this to Master and it would have gone live anyway lol. The only thing I wanted to check was how it renders in edge and add the revised version that Callum posted. I'm behind on keyboard time at the mo

**Pull request merged**
