### PR TITLE
New structure sponsorship program stuff

### PR DESCRIPTION
**Pull request by AndyGaskell**
Hi @dannyockilson and @sunscreem 

This is the sponsorship idea I mentioned last week.  It's a bit rough, but seemed like an ok start.  I was going to do the PR at the weekend, but didn't get time.

Not sure if this is just a discussion starter or if you both feels it's ok as a first pass, either way it seems like it might be useful.

It could probably do with some placeholder logos, but I couldn't quickly find any good royalty free ones.  Also, there is some inline CSS, which could be moved into the CSS file.

Danny, I'll chuck you the dough for the two micro sponsors :)

### CODE REVIEW

**Comment by sunscreem** [comment]
Cheers Andy... Backlogged with work just now but I'll get to this ASAP :)

**Comment by AndyGaskell** [comment]
Thanks @sunscreem it's all pretty trivial, be fine to just merge it I think.

Long as @dannyockilson is happy with the general principles of the sponsorship stuff, as a first go round.

**Comment by dannyockilson** [comment]
Looks good @AndyGaskell probs worth removing Jetbrains... they don't give us stuff anymore :(

Thanks for sorting this out though! Really appreciate the kick up the arse ;)

**Review by dannyockilson — CHANGES_REQUESTED** [review]
Remove jetbrains logo :)

**Comment by AndyGaskell** [comment]
I removed jetbrains, but kept the "Other Supporters" section, with the blurb "If you'd like to support the group in other ways, please get in touch.  We're always looking for books, subscriptions and that sort of thing to raffle off at meetups."

**Review by dannyockilson — APPROVED** [review]
lgtm

**Pull request merged**
