### PR TITLE
Events and stuff

### PR DESCRIPTION
**Pull request by dannyockilson**
* Fixed a few bugs with images (logo/icons) when the url has multiple segments.
* Added basic docker files so I can run it without having to install virtualbox again ;) (happy to gitignore these if they complicate stuff)
* Added links on the community page for other events in Aberdeen and other PHP events in Scotland
* Split out separate pages for community events (one each)

NB: I have not taken the community events off the events page but can do if that's ok with peeps.

### CODE REVIEW

**Comment by dannyockilson** [comment]
I decided just to remove the docker stuff (cause that makes the name of the branch even more helpful :p) Since I doubt anyone else will be using it

**Comment by sunscreem** [comment]
Does the docker stuff only add a config file or two? If so - it make sense to leave it in imo

**Comment by dannyockilson** [comment]
It could be cut back a bit I just stuck in a generic nginx/php one. Two dockerfile, a docker-compose.yml an nginx config file and a makefile with a few helpers

**Comment by sunscreem** [comment]
I don't see any reason to remove it. Its going to be a time saver for those docker inclined.

**Comment by dannyockilson** [comment]
Pushed that up now :)

**Comment by dannyockilson** [comment]
If you wouldn't mind having a look over the actual code changes and make sure it all makes sense/done in a normal way that'd be ace @sunscreem

**Comment by sunscreem** [comment]
Will do - hopefully this afternoon but it might be sunday due to a deadline I'm on and rugby.

**Comment by sunscreem** [comment]
Just had a quick look danny and I can see a couple of minor things - for example you've created a `resources/views/components` folder but in laravel there is a thing called 'components' and 'slots', so the terminology/folder name is usually `resources/views/partials`. Would you be offended if I made some minor tweaks and posted them on this pr for you to look at?

**Comment by dannyockilson** [comment]
That's cool the name is 100% irrelevant in this case ;) will need to look at what laravel components are. Guessing they're new in 5.something?

**Comment by dannyockilson** [comment]
Ah yeah those things we talked about at the meetup a few months ago :P tbf you could move that pack into the main file. I was expecting to need them in multiple places but ended up just reusing the events template as it's fairly flexible :)

**Comment by dannyockilson** [comment]
Just updated that to remove component/events file :)

**Comment by sunscreem** [comment]
lol - I would have kept it in and put it in a "partial" instead. Saying that there's lot about this project that I would do differently but striking the balance between keeping it simple for n00bs versus making it less cluttered is tricky. Another one for the list of things to discuss at the next lunch ;)

**Comment by sunscreem** [comment]
Another example of that - you've added named routes for the new links you've added, but I didn't use named routes elsewhere. Starting to lean towards going "full laravel" on this bad boy hahaa

**Comment by dannyockilson** [comment]
Yeah I wasn't sure about the named routes (noticed they'd not been used elsewhere) but using that syntax in the templates feels nicer to me? But agree striking the balance is tricky don't want to go too far and put people off but on the other side I'm not completely convinced people other than us, billy and andy will actually ever update this :p

**Comment by sunscreem** [comment]
Yeah, agreed.

Anyway - merging this now. Good to go.

Sorry it took a while, I'm still getting use to this kind of workflow too :)

**Pull request merged**
