### PR TITLE
Revert "Just a tidy up of p tags in li tags, very minor"

### PR DESCRIPTION
**Pull request by sunscreem**
Reverts AberdeenPHP/AberdeenPHP-Website#46

image

This broke some images further down lol.

You got a sec to double check it andy? I've reverted it for now. If not I'll have a look myself when I get a min

### CODE REVIEW

**Comment by sunscreem** [comment]
@AndyGaskell Forgot to tag you

**Comment by AndyGaskell** [comment]
Ah, yea, I'd not spotted that.

We could tweak the CSS, from...
```
.community li {
    margin-bottom: 20px;
}
```
...to...
```
.community li {
    margin-bottom: 30px;
}
```

Then it'll look like...
the_community_-_aberdeen_php_user_group_-_2018-01-31_14 59 36


What do you think Rob?
@sunscreem

**Comment by sunscreem** [comment]
Go for it - looks spot on to me :)

**Comment by AndyGaskell** [comment]
See fix in #53

**Pull request merged**
