### PR TITLE
Contact form recaptcha

### PR DESCRIPTION
**Pull request by evocate**
Implemented ReCaptcha to improve Danny's quality of life a little.

The following need to be added to the live environment:

RECAPTCHA_SITE_KEY
RECAPTCHA_SECRET_KEY

**Notes**
1.  For now, server side verification only occurs on a 'production' environment.  This feels too hacky for me.  I like being able to test real APIs with my tests which I am guessing is it not possible here.  Otherwise I could mock the ReCaptcha Client I guess, although I have never created a custom mock with phpunit.  Thoughts?
2. I was going to add a config file for the ReCaptcha keys and noticed you removed one for bugsnag. I can do it as opposed to referencing env() directly.
3. I have not implemented any sort of check to see if secret key has been set before the ReCaptcha client dives in.  Was wondering if and how you want to implement exception handling and logging.

### CODE REVIEW

**Comment by sunscreem** [comment]
`improve Danny's quality of life a little.` = Ambitious. 

1. For the testing - do you know there is a special key and secret you can put in that forces recaptcha to always pass in [local and test setups](https://developers.google.com/recaptcha/docs/faq)? Would that make a difference here?

2. If I removed one for bugsnag I suspect it wasn't needed or that's an error. Go for it with the config for this. 

3. I've got bugsnag running already so I would get told straight away if we'd screwed anything up here I think.

Should we try using the recently announced V3 here? Or is that what you've gone for (I've not actually looked at the PR other than the notes)

**Comment by evocate** [comment]
@sunscreem 

1. I have implemented the "always passes" reCAPTCHA test key into the tests.  It works, however I do notice on that site it says:

> For reCAPTCHA v3, create a separate key for testing environments. Scores may not be accurate as reCAPTCHA v3 relies on seeing real traffic.

The token validation endpoint is the same for V2 and V3.  But it won't work when actually using the contact form with those keys as I am using V3 for this.

2. Added a config for reCAPTCHA.

3. No problem.

**Comment by evocate** [comment]
I've also updated the key names as seen in the .env.example:

RECAPTCHA_KEY=
RECAPTCHA_SECRET=

**Comment by sunscreem** [comment]
Just want to say I've seen this Richard and I'll have a proper look when I get a min :)

**Review by sunscreem — APPROVED** [review]

**Comment by AndyGaskell** [comment]
Sounds good :+1:

**Pull request merged**
