### PR TITLE
Just a tidy up of p tags in li tags, very minor

### PR DESCRIPTION
**Pull request by AndyGaskell**
the p tags were causing the paragraph to be much lower than the li bullet.

the_community_-_aberdeen_php_user_group_-_2017-09-26_23 54 29

### CODE REVIEW

**Comment by AndyGaskell** [comment]
Also fixed the missing p tag on the first paragraph.

**Comment by AndyGaskell** [comment]
Before...
the_community_-_aberdeen_php_user_group_-_2017-09-27_00 03 45

After...
the_community_-_aberdeen_php_user_group_-_2017-09-27_00 04 38

**Comment by sunscreem** [comment]
Andy - this never got merged. My apologies I must have missed it.

Thing is - I think the issues may have been resolved in other commits? Can you double check if this still need merged?

**Comment by sunscreem** [comment]
Closing as no reply from andy. Will re-open no problem.

**Comment by AndyGaskell** [comment]
Hey Rob, sorry, missed your reply back in October.  The issue the PR fixes is still there, see https://aberdeenphp.co.uk/community

It's no biggie, just a visual thing.

the_community_-_aberdeen_php_user_group_-_2018-01-31_12 53 56
Firefox 58.0 (64-bit)

screenshot_2018-01-31_12-56-24
Chrome 64.0.3282.119 (Official Build) (64-bit)

**Pull request merged**
